################################################################################
## unit_test/test/core/SConscript
##
## Copyright 2011, Jeffrey Hellrung.
## Distributed under the Boost Software License, Version 1.0.  (See accompanying
## file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
################################################################################

Import('env', 'LibraryInstall')
LibraryInstall(env, target='sake_core_test', source=Glob('*.cpp') + Glob('*/*.cpp'))
