/*******************************************************************************
 * boost_ext/preprocessor/keyword/access.hpp
 *
 * Copyright 2011, Jeffrey Hellrung.
 * Distributed under the Boost Software License, Version 1.0.  (See accompanying
 * file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
 *
 * #define SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_ACCESS( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_ACCESS( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_REMOVE_PREFIX_ACCESS( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_REMOVE_SUFFIX_ACCESS( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_GET_PREFIX_ACCESS( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_GET_SUFFIX_ACCESS( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_GET_PREFIX_ACCESS_COLON( X )
 * #define SAKE_BOOST_EXT_PP_KEYWORD_GET_SUFFIX_ACCESS_COLON( X )
 ******************************************************************************/

#ifndef SAKE_BOOST_EXT_PREPROCESSOR_KEYWORD_ACCESS_HPP
#define SAKE_BOOST_EXT_PREPROCESSOR_KEYWORD_ACCESS_HPP

#include <boost/preprocessor/cat.hpp>

#include <sake/boost_ext/preprocessor/keyword/has_prefix.hpp>
#include <sake/boost_ext/preprocessor/keyword/private.hpp>
#include <sake/boost_ext/preprocessor/keyword/protected.hpp>
#include <sake/boost_ext/preprocessor/keyword/public.hpp>
#include <sake/boost_ext/preprocessor/keyword/remove_prefix.hpp>

#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_private   ( )
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_protected ( )
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_public    ( )
#define   private_SAKE_BOOST_EXT_PP_KEYWORD_ACCESS ( )
#define protected_SAKE_BOOST_EXT_PP_KEYWORD_ACCESS ( )
#define    public_SAKE_BOOST_EXT_PP_KEYWORD_ACCESS ( )

#define SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_ACCESS( X ) \
    SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX( X, SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_ )
#define SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_ACCESS( X ) \
    SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX( X, _SAKE_BOOST_EXT_PP_KEYWORD_ACCESS )
#define SAKE_BOOST_EXT_PP_KEYWORD_REMOVE_PREFIX_ACCESS( X ) \
    SAKE_BOOST_EXT_PP_KEYWORD_REMOVE_PREFIX( X, SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_ )
#define SAKE_BOOST_EXT_PP_KEYWORD_REMOVE_SUFFIX_ACCESS( X ) \
    SAKE_BOOST_EXT_PP_KEYWORD_SUFFIX_PREFIX( X, _SAKE_BOOST_EXT_PP_KEYWORD_ACCESS )

#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_000
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_100 private
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_010 protected
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_001 public

#define SAKE_BOOST_EXT_PP_KEYWORD_GET_PREFIX_ACCESS( X ) \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_, \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_PRIVATE  ( X ), \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_PROTECTED( X ), \
                  SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_PUBLIC   ( X ) ) ) )

#define SAKE_BOOST_EXT_PP_KEYWORD_GET_SUFFIX_ACCESS( X ) \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_, \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_PRIVATE  ( X ), \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_PROTECTED( X ), \
                  SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_PUBLIC   ( X ) ) ) )

#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_COLON_000
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_COLON_100 private:
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_COLON_010 protected:
#define SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_COLON_001 public:

#define SAKE_BOOST_EXT_PP_KEYWORD_GET_PREFIX_ACCESS_COLON( X ) \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_COLON_, \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_PRIVATE  ( X ), \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_PROTECTED( X ), \
                  SAKE_BOOST_EXT_PP_KEYWORD_HAS_PREFIX_PUBLIC   ( X ) ) ) )

#define SAKE_BOOST_EXT_PP_KEYWORD_GET_SUFFIX_ACCESS_COLON( X ) \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_ACCESS_COLON_, \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_PRIVATE  ( X ), \
    BOOST_PP_CAT( SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_PROTECTED( X ), \
                  SAKE_BOOST_EXT_PP_KEYWORD_HAS_SUFFIX_PUBLIC   ( X ) ) ) )

#endif // #ifndef SAKE_BOOST_EXT_PREPROCESSOR_KEYWORD_ACCESS_HPP
