################################################################################
## unit_test/runner/test/SConscript
##
## Copyright 2011, Jeffrey Hellrung.
## Distributed under the Boost Software License, Version 1.0.  (See accompanying
## file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
################################################################################

Import('env', 'ProgramInstall')
env_clone = env.Clone()
env_clone.Prepend(LIBS=['sake_test_test', 'sake_test'])
ProgramInstall(env_clone, target='test_runner', source=['main.cpp'])
