################################################################################
## lib/core/SConscript
##
## Copyright 2011, Jeffrey Hellrung.
## Distributed under the Boost Software License, Version 1.0.  (See accompanying
## file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
################################################################################

Import('env', 'auto_Library')
auto_Library(env, target='sake_core', source=Glob('*/*.cpp'))
